# Generated by Django 2.1.5 on 2020-04-28 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_atches', models.IntegerField(default=0)),
                ('batting_innings', models.IntegerField(default=0)),
                ('batting_notouts', models.IntegerField(default=0)),
                ('batting_Runs', models.IntegerField(default=0)),
                ('batting_HS', models.IntegerField(default=0)),
                ('batting_avg', models.FloatField(default=0.0)),
                ('batting_ballsfaced', models.IntegerField(default=0)),
                ('batting_strikerate', models.FloatField(default=0)),
                ('batting_hundreds', models.IntegerField(default=0)),
                ('batting_fifty', models.IntegerField(default=0)),
                ('batting_twohundreds', models.IntegerField(default=0)),
                ('batting_fours', models.IntegerField(default=0)),
                ('batting_sixes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BowlPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowl_matches', models.FloatField(default=0)),
                ('bowl_innings', models.IntegerField(default=0)),
                ('bowl_noofballs', models.IntegerField(default=0)),
                ('bowl_runs', models.IntegerField(default=0)),
                ('bowl_wkts', models.IntegerField(default=0)),
                ('bowl_wickets_lbw', models.IntegerField(default=0)),
                ('bowl_wickets_economy', models.IntegerField(default=0)),
                ('bowl_wickets_stumped', models.IntegerField(default=0)),
                ('bowl_wickets_avgt', models.IntegerField(default=0)),
                ('bowl_wickets_SR', models.IntegerField(default=0)),
                ('bowl_five_wickets', models.IntegerField(default=0)),
                ('bowl_ten_wickets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clubstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_catches', models.IntegerField(default=0)),
                ('field_run_outs', models.IntegerField(default=0)),
                ('field_stumped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clubstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Clubstate')),
            ],
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('overs', models.FloatField()),
                ('declared', models.BooleanField()),
                ('extras_byes', models.IntegerField(default=0)),
                ('extras_leg_byes', models.IntegerField(default=0)),
                ('extras_wides', models.IntegerField(default=0)),
                ('extras_no_balls', models.IntegerField(default=0)),
                ('extras_penalties', models.IntegerField(default=0)),
                ('extras_total', models.IntegerField(default=0)),
                ('highlights', models.TextField(default='')),
                ('complete_innings', models.BooleanField(default=False)),
                ('inning_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toss_won_by_team_id', models.CharField(max_length=8)),
                ('toss', models.CharField(max_length=512)),
                ('batted_first', models.CharField(max_length=8)),
                ('result', models.CharField(max_length=2)),
                ('result_description', models.CharField(max_length=512)),
                ('result_applied_to', models.CharField(max_length=8)),
                ('match_notes', models.TextField()),
                ('number_of_players', models.IntegerField(default=0)),
                ('full_scorecard', models.BooleanField(default=False)),
                ('processing_issue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('imageUri', models.ImageField(upload_to='images/', verbose_name='image')),
                ('JerseyNumber', models.IntegerField()),
                ('BirthPlace', models.CharField(default=False, max_length=10)),
                ('BirthDate', models.CharField(default=False, max_length=30)),
                ('Role', models.CharField(default=False, max_length=20)),
                ('BattingStyle', models.CharField(default=False, max_length=20)),
                ('BowlingStyle', models.CharField(default=False, max_length=20)),
                ('clubstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubstate', to='CricketDetails.Clubstate')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('logo1', models.ImageField(upload_to='images/', verbose_name='logo1')),
                ('logo2', models.ImageField(upload_to='images/', verbose_name='logo2')),
                ('logo3', models.ImageField(upload_to='images/', verbose_name='logo3')),
                ('clubstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Clubstate')),
            ],
        ),
        migrations.AddField(
            model_name='playerstructure',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier1', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.MatchDate'),
        ),
        migrations.AddField(
            model_name='match',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Ground'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='inning',
            name='bat_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bat_team', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='inning',
            name='bowl_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowl_team', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='inning',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='fieldperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='fieldperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.PlayerStructure'),
        ),
        migrations.AddField(
            model_name='bowlperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='bowlperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerbowlperf', to='CricketDetails.PlayerStructure'),
        ),
        migrations.AddField(
            model_name='batperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdetails', to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='batperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerbatperf', to='CricketDetails.PlayerStructure'),
        ),
    ]
