# Generated by Django 2.1.5 on 2020-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstructure',
            name='imageUri',
            field=models.ImageField(upload_to='static/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teamstructure',
            name='logo',
            field=models.ImageField(upload_to='static/images', verbose_name='logo'),
        ),
    ]
