# Generated by Django 2.1.5 on 2020-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0002_auto_20200425_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstructure',
            name='imageUri',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teamstructure',
            name='logo',
            field=models.ImageField(upload_to='images/', verbose_name='logo'),
        ),
    ]
