# Generated by Django 2.1.5 on 2020-04-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0002_auto_20200429_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='batperformance',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='CricketDetails.TeamStructure'),
        ),
    ]
