# Generated by Django 2.1.5 on 2020-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0003_auto_20200425_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstructure',
            name='summary',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
