# Generated by Django 2.1.5 on 2020-04-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0003_batperformance_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldperformance',
            name='match',
        ),
        migrations.RemoveField(
            model_name='fieldperformance',
            name='player',
        ),
        migrations.AddField(
            model_name='bowlperformance',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country1', to='CricketDetails.TeamStructure'),
        ),
        migrations.DeleteModel(
            name='FieldPerformance',
        ),
    ]
