# Generated by Django 2.1.5 on 2020-04-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0004_auto_20200429_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='clubstate',
        ),
        migrations.RemoveField(
            model_name='inning',
            name='bat_team',
        ),
        migrations.RemoveField(
            model_name='inning',
            name='bowl_team',
        ),
        migrations.RemoveField(
            model_name='inning',
            name='match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='batted_first',
        ),
        migrations.RemoveField(
            model_name='match',
            name='full_scorecard',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='match',
            name='processing_issue',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_applied_to',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_description',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_won_by_team_id',
        ),
        migrations.AddField(
            model_name='match',
            name='League',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='Team1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team1logo',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Team1 logo'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='CricketDetails.TeamStructure'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team2logo',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Team2 logo'),
        ),
        migrations.AddField(
            model_name='match',
            name='clubstate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CricketDetails.Clubstate'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ground',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Ground',
        ),
        migrations.DeleteModel(
            name='Inning',
        ),
    ]
