# Generated by Django 2.1.5 on 2020-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0004_teamstructure_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstructure',
            name='logo',
        ),
        migrations.AddField(
            model_name='teamstructure',
            name='logo1',
            field=models.ImageField(default=False, upload_to='images/', verbose_name='logo1'),
        ),
        migrations.AddField(
            model_name='teamstructure',
            name='logo2',
            field=models.ImageField(default=False, upload_to='images/', verbose_name='logo2'),
        ),
        migrations.AddField(
            model_name='teamstructure',
            name='logo3',
            field=models.ImageField(default=False, upload_to='images/', verbose_name='logo3'),
        ),
        migrations.AlterField(
            model_name='teamstructure',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
