# Generated by Django 2.1.5 on 2020-04-29 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0005_auto_20200429_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='MatchDate',
        ),
    ]
