# Generated by Django 2.1.5 on 2020-04-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0006_auto_20200425_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umpireassignment',
            name='match',
        ),
        migrations.RemoveField(
            model_name='umpireassignment',
            name='umpire',
        ),
        migrations.RemoveField(
            model_name='playerstructure',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='playerstructure',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifier1', to='CricketDetails.TeamStructure'),
        ),
        migrations.DeleteModel(
            name='Umpire',
        ),
        migrations.DeleteModel(
            name='UmpireAssignment',
        ),
    ]
