# Generated by Django 2.1.5 on 2020-04-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0007_auto_20200426_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batperformance',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdetails', to='CricketDetails.Match'),
        ),
        migrations.AlterField(
            model_name='batperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerbatperf', to='CricketDetails.PlayerStructure'),
        ),
        migrations.AlterField(
            model_name='bowlperformance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerbowlperf', to='CricketDetails.PlayerStructure'),
        ),
    ]
