# Generated by Django 2.1.5 on 2020-04-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0007_auto_20200429_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1Score', models.IntegerField(default=0)),
                ('team2Score', models.IntegerField(default=0)),
                ('matches_between', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_between', to='CricketDetails.Match')),
            ],
        ),
    ]
