# Generated by Django 2.1.5 on 2020-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0009_auto_20200430_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Elected_to',
            field=models.BooleanField(choices=[('True', 'Bat'), ('False', 'Bowl')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Toss_won_by',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
