# Generated by Django 2.1.5 on 2020-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0011_auto_20200430_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Elected_to',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
    ]
