# Generated by Django 2.1.5 on 2020-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0012_auto_20200430_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Elected_to',
            field=models.CharField(choices=[('Bat', 'Bat'), ('Bat', 'Bowl')], max_length=100),
        ),
    ]
