# Generated by Django 2.1.5 on 2020-04-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0013_auto_20200430_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cont', to='CricketDetails.TeamStructure')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='team1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='score',
            name='team2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='CricketDetails.Match'),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='team_won',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to='CricketDetails.Score'),
        ),
    ]
