# Generated by Django 2.1.5 on 2020-04-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0014_auto_20200430_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team2',
        ),
    ]
