# Generated by Django 2.1.5 on 2020-04-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CricketDetails', '0016_auto_20200430_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='Team1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='Team2',
        ),
    ]
